// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/interfaces/services/access_token.go

// Package mocks is a generated GoMock package.
package mocks

import (
	commands "auth-service/internal/domain/dto/tokens/commands"
	results "auth-service/internal/domain/dto/tokens/results"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAccessToken is a mock of AccessToken interface.
type MockAccessToken struct {
	ctrl     *gomock.Controller
	recorder *MockAccessTokenMockRecorder
}

// MockAccessTokenMockRecorder is the mock recorder for MockAccessToken.
type MockAccessTokenMockRecorder struct {
	mock *MockAccessToken
}

// NewMockAccessToken creates a new mock instance.
func NewMockAccessToken(ctrl *gomock.Controller) *MockAccessToken {
	mock := &MockAccessToken{ctrl: ctrl}
	mock.recorder = &MockAccessTokenMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccessToken) EXPECT() *MockAccessTokenMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockAccessToken) Generate(command commands.Generate) (*results.Generate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", command)
	ret0, _ := ret[0].(*results.Generate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockAccessTokenMockRecorder) Generate(command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockAccessToken)(nil).Generate), command)
}

// Parse mocks base method.
func (m *MockAccessToken) Parse(command commands.Parse) (*results.Parse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", command)
	ret0, _ := ret[0].(*results.Parse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockAccessTokenMockRecorder) Parse(command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockAccessToken)(nil).Parse), command)
}
