// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/interfaces/repositories/access_token_repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	commands "auth-service/internal/domain/dto/tokens/commands"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAccessTokenRepo is a mock of AccessTokenRepo interface.
type MockAccessTokenRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAccessTokenRepoMockRecorder
}

// MockAccessTokenRepoMockRecorder is the mock recorder for MockAccessTokenRepo.
type MockAccessTokenRepoMockRecorder struct {
	mock *MockAccessTokenRepo
}

// NewMockAccessTokenRepo creates a new mock instance.
func NewMockAccessTokenRepo(ctrl *gomock.Controller) *MockAccessTokenRepo {
	mock := &MockAccessTokenRepo{ctrl: ctrl}
	mock.recorder = &MockAccessTokenRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccessTokenRepo) EXPECT() *MockAccessTokenRepoMockRecorder {
	return m.recorder
}

// IsRevoked mocks base method.
func (m *MockAccessTokenRepo) IsRevoked(ctx context.Context, jti string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRevoked", ctx, jti)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsRevoked indicates an expected call of IsRevoked.
func (mr *MockAccessTokenRepoMockRecorder) IsRevoked(ctx, jti interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRevoked", reflect.TypeOf((*MockAccessTokenRepo)(nil).IsRevoked), ctx, jti)
}

// Revoke mocks base method.
func (m *MockAccessTokenRepo) Revoke(ctx context.Context, command commands.Revoke) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, command)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockAccessTokenRepoMockRecorder) Revoke(ctx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockAccessTokenRepo)(nil).Revoke), ctx, command)
}
