// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/interfaces/repositories/refresh_token_repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	commands "auth-service/internal/domain/dto/tokens/commands"
	results "auth-service/internal/domain/dto/tokens/results"
	tx "auth-service/internal/domain/interfaces/tx"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRefreshTokenRepo is a mock of RefreshTokenRepo interface.
type MockRefreshTokenRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenRepoMockRecorder
}

// MockRefreshTokenRepoMockRecorder is the mock recorder for MockRefreshTokenRepo.
type MockRefreshTokenRepoMockRecorder struct {
	mock *MockRefreshTokenRepo
}

// NewMockRefreshTokenRepo creates a new mock instance.
func NewMockRefreshTokenRepo(ctrl *gomock.Controller) *MockRefreshTokenRepo {
	mock := &MockRefreshTokenRepo{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenRepo) EXPECT() *MockRefreshTokenRepoMockRecorder {
	return m.recorder
}

// AddTx mocks base method.
func (m *MockRefreshTokenRepo) AddTx(ctx context.Context, tx tx.Tx, command commands.Add) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTx", ctx, tx, command)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTx indicates an expected call of AddTx.
func (mr *MockRefreshTokenRepoMockRecorder) AddTx(ctx, tx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTx", reflect.TypeOf((*MockRefreshTokenRepo)(nil).AddTx), ctx, tx, command)
}

// BeginTx mocks base method.
func (m *MockRefreshTokenRepo) BeginTx(ctx context.Context) (tx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(tx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockRefreshTokenRepoMockRecorder) BeginTx(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockRefreshTokenRepo)(nil).BeginTx), ctx)
}

// DeleteByTokenTx mocks base method.
func (m *MockRefreshTokenRepo) DeleteByTokenTx(ctx context.Context, tx tx.Tx, command commands.DeleteByToken) (*results.Delete, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByTokenTx", ctx, tx, command)
	ret0, _ := ret[0].(*results.Delete)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByTokenTx indicates an expected call of DeleteByTokenTx.
func (mr *MockRefreshTokenRepoMockRecorder) DeleteByTokenTx(ctx, tx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByTokenTx", reflect.TypeOf((*MockRefreshTokenRepo)(nil).DeleteByTokenTx), ctx, tx, command)
}

// UpdateByTokenTx mocks base method.
func (m *MockRefreshTokenRepo) UpdateByTokenTx(ctx context.Context, tx tx.Tx, command commands.UpdateByToken) (*results.Update, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByTokenTx", ctx, tx, command)
	ret0, _ := ret[0].(*results.Update)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateByTokenTx indicates an expected call of UpdateByTokenTx.
func (mr *MockRefreshTokenRepoMockRecorder) UpdateByTokenTx(ctx, tx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByTokenTx", reflect.TypeOf((*MockRefreshTokenRepo)(nil).UpdateByTokenTx), ctx, tx, command)
}

// UpdateByUserIDTx mocks base method.
func (m *MockRefreshTokenRepo) UpdateByUserIDTx(ctx context.Context, tx tx.Tx, command commands.UpdateByUserID) (*results.Update, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByUserIDTx", ctx, tx, command)
	ret0, _ := ret[0].(*results.Update)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateByUserIDTx indicates an expected call of UpdateByUserIDTx.
func (mr *MockRefreshTokenRepoMockRecorder) UpdateByUserIDTx(ctx, tx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByUserIDTx", reflect.TypeOf((*MockRefreshTokenRepo)(nil).UpdateByUserIDTx), ctx, tx, command)
}
