// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/interfaces/services/token.go

// Package mocks is a generated GoMock package.
package mocks

import (
	commands "auth-service/internal/domain/dto/tokens/commands"
	results "auth-service/internal/domain/dto/tokens/results"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockToken is a mock of Token interface.
type MockToken struct {
	ctrl     *gomock.Controller
	recorder *MockTokenMockRecorder
}

// MockTokenMockRecorder is the mock recorder for MockToken.
type MockTokenMockRecorder struct {
	mock *MockToken
}

// NewMockToken creates a new mock instance.
func NewMockToken(ctrl *gomock.Controller) *MockToken {
	mock := &MockToken{ctrl: ctrl}
	mock.recorder = &MockTokenMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockToken) EXPECT() *MockTokenMockRecorder {
	return m.recorder
}

// ValidateToken mocks base method.
func (m *MockToken) ValidateToken(ctx context.Context, command commands.Validate) (*results.Validate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", ctx, command)
	ret0, _ := ret[0].(*results.Validate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockTokenMockRecorder) ValidateToken(ctx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockToken)(nil).ValidateToken), ctx, command)
}
