// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/interfaces/repositories/user_repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	commands "auth-service/internal/domain/dto/user/commands"
	results "auth-service/internal/domain/dto/user/results"
	tx "auth-service/internal/domain/interfaces/tx"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserRepo is a mock of UserRepo interface.
type MockUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoMockRecorder
}

// MockUserRepoMockRecorder is the mock recorder for MockUserRepo.
type MockUserRepoMockRecorder struct {
	mock *MockUserRepo
}

// NewMockUserRepo creates a new mock instance.
func NewMockUserRepo(ctrl *gomock.Controller) *MockUserRepo {
	mock := &MockUserRepo{ctrl: ctrl}
	mock.recorder = &MockUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepo) EXPECT() *MockUserRepoMockRecorder {
	return m.recorder
}

// AddRoleTx mocks base method.
func (m *MockUserRepo) AddRoleTx(ctx context.Context, tx tx.Tx, command commands.AssignRole) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRoleTx", ctx, tx, command)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRoleTx indicates an expected call of AddRoleTx.
func (mr *MockUserRepoMockRecorder) AddRoleTx(ctx, tx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRoleTx", reflect.TypeOf((*MockUserRepo)(nil).AddRoleTx), ctx, tx, command)
}

// AddTx mocks base method.
func (m *MockUserRepo) AddTx(ctx context.Context, tx tx.Tx, command commands.Add) (*results.Add, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTx", ctx, tx, command)
	ret0, _ := ret[0].(*results.Add)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTx indicates an expected call of AddTx.
func (mr *MockUserRepoMockRecorder) AddTx(ctx, tx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTx", reflect.TypeOf((*MockUserRepo)(nil).AddTx), ctx, tx, command)
}

// BeginTx mocks base method.
func (m *MockUserRepo) BeginTx(ctx context.Context) (tx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(tx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockUserRepoMockRecorder) BeginTx(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockUserRepo)(nil).BeginTx), ctx)
}

// GetByIDTx mocks base method.
func (m *MockUserRepo) GetByIDTx(ctx context.Context, tx tx.Tx, userID int64) (*results.Get, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDTx", ctx, tx, userID)
	ret0, _ := ret[0].(*results.Get)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDTx indicates an expected call of GetByIDTx.
func (mr *MockUserRepoMockRecorder) GetByIDTx(ctx, tx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDTx", reflect.TypeOf((*MockUserRepo)(nil).GetByIDTx), ctx, tx, userID)
}

// GetByLoginTx mocks base method.
func (m *MockUserRepo) GetByLoginTx(ctx context.Context, tx tx.Tx, command commands.GetByLogin) (*results.Get, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByLoginTx", ctx, tx, command)
	ret0, _ := ret[0].(*results.Get)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByLoginTx indicates an expected call of GetByLoginTx.
func (mr *MockUserRepoMockRecorder) GetByLoginTx(ctx, tx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByLoginTx", reflect.TypeOf((*MockUserRepo)(nil).GetByLoginTx), ctx, tx, command)
}

// GetUsers mocks base method.
func (m *MockUserRepo) GetUsers(ctx context.Context, tx tx.Tx, command commands.GetUsers) (*results.GetUsers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsers", ctx, tx, command)
	ret0, _ := ret[0].(*results.GetUsers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsers indicates an expected call of GetUsers.
func (mr *MockUserRepoMockRecorder) GetUsers(ctx, tx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockUserRepo)(nil).GetUsers), ctx, tx, command)
}

// RemoveRoleTx mocks base method.
func (m *MockUserRepo) RemoveRoleTx(ctx context.Context, tx tx.Tx, command commands.RevokeRole) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveRoleTx", ctx, tx, command)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveRoleTx indicates an expected call of RemoveRoleTx.
func (mr *MockUserRepoMockRecorder) RemoveRoleTx(ctx, tx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRoleTx", reflect.TypeOf((*MockUserRepo)(nil).RemoveRoleTx), ctx, tx, command)
}

// UpdatePasswordTx mocks base method.
func (m *MockUserRepo) UpdatePasswordTx(ctx context.Context, tx tx.Tx, command commands.UpdatePassword) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePasswordTx", ctx, tx, command)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePasswordTx indicates an expected call of UpdatePasswordTx.
func (mr *MockUserRepoMockRecorder) UpdatePasswordTx(ctx, tx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePasswordTx", reflect.TypeOf((*MockUserRepo)(nil).UpdatePasswordTx), ctx, tx, command)
}

// UpdateTx mocks base method.
func (m *MockUserRepo) UpdateTx(ctx context.Context, tx tx.Tx, command commands.Update) (*results.Update, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTx", ctx, tx, command)
	ret0, _ := ret[0].(*results.Update)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTx indicates an expected call of UpdateTx.
func (mr *MockUserRepoMockRecorder) UpdateTx(ctx, tx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTx", reflect.TypeOf((*MockUserRepo)(nil).UpdateTx), ctx, tx, command)
}
